<!-- Navbar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="div-logo" href="#">
            <img src="./assets/CollabSpot-removebg-preview.png" alt="CollabSpot" class="logo">
        </div>
        <div class="d-flex">
            <button class="btn" type="submit"><a href="#" class="home">Home</a></button>
            <button class="btn" type="submit"><a href="#services">Services</a></button>
            <button class="btn" type="submit"><a href="#about">About</a></button>
            <button class="btn sign modal-trigger" type="submit"><a href="#">Sign in</a></button>
            <button class="btn sign modal-trigger1" type="submit"><a href="#">Sign up</a></button>
        </div>
    </div>
</nav>
<!-- 1er partie de page home -->
<div class="grande-partie">
    <div class="text">
        <h2 id="collab">CollabSpot</h2>
        <p>At CollabSpot, we believe in the power of collaboration to transform ordinary
            ideas into extraordinary ones. Our revolutionary platform provides a dynamic
            space where creative minds come together, exchange ideas, and innovate collectively</p>
    </div>
    <div class="image">
        <img src="./assets/acceuil.jpg" alt="Image à droite">
    </div>
</div>
<!-- sign in and sign up-->
<section>
    <?php
           
           include 'Login/sign_in.php';
           include 'Signup/sign_up.php';
           
        ?>
</section>
<!-- Services -->
<section id="services">
    <div class="container">
        <h2>Our Services</h2>
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <i class='bx bxs-quote-alt-left'></i>
                <h3>Communication Section</h3>
                <p>Highlight communication features such as forums, online discussions, discussion groups, etc</p>
            </div>
            <div class="col-md-4 col-sm-6 my-3">
                <i class='bx bxs-quote-alt-right'></i>
                <h3>Problem Sharing</h3>
                <p>Allow users to post issues or questions to get help from the community</p>
            </div>
            <div class="col-md-4 col-sm-6">
                <i class='bx bxs-quote-alt-left'></i>
                <h3>Positive Feedback</h3>
                <p>Showcase testimonials from members who have successfully solved problems through
                    community support</p>
            </div>
        </div>
    </div>
</section>
<!-- About Us -->
<section class="aboutus" id="about">
    <div class="container">
        <h2>About Us</h2>
        <p>We are a team passionate about innovation and design. We founded Collab Spot to assist
            you in achieving your professional or personal goals. For this, we leverage our expertise
            to design innovative solutions that simplify your daily life
        </p>
        <p>
            We use our technical expertise and design skills to create innovative solutions that meet
            the specific needs of each client
        </p>
        <div class="cards">
            <div class="card first">
                <img src="./assets/bouthaina.jpg" alt="Web development">
                <div class="card-content">
                    <h2>
                        Bouthaina Belghith
                    </h2>
                    <p>
                        Passionate about user interface and user experience, this development student
                        specializes in front-end technologies. Proficient in languages such as HTML,
                        CSS, and JavaScript, she excels in creating interactive interfaces and stays
                        up-to-date with the latest web design trends
                    </p>
                </div>
            </div>
            <div class="card second">
                <img src="./assets/akrem.jpg" alt="designer">
                <div class="card-content">
                    <h2>
                        Akrem Zâabi
                    </h2>
                    <p>
                        This back-end development student combines a strong understanding of server-side
                        languages like Python, Java, or Node.js with expertise in database management.
                        Passionate about building robust applications, they excel in designing high-performance
                        and scalable backend systems
                    </p>
                </div>
            </div>
            <div class="card third">
                <img src="./assets/mourad.jpg" alt="Web development">
                <div class="card-content">
                    <h2>
                        Mourad Soltan
                    </h2>
                    <p>
                        With a holistic view of web development, this full-stack development
                        student excels in both front-end and back-end technologies. Versatile
                        and results-driven, they enjoy working on comprehensive projects, from
                        initial design to final implementation.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Footer -->
<footer class="footer-distributed">
    <div class="footer-left">
        <img src="./assets/CollabSpot-removebg-preview.png" alt="logo">
        <p class="footer-links">
            <a href="#collab" class="link-1">Home</a>
            <a href="#services">Services</a>
            <a href="#about">About</a>
            <a href="#">Contact</a>
        </p>
        <p class="footer-company-name">CollabSpot © 2023</p>
    </div>
    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker"></i>
            <p><span>Isetb</span> Bizerte, Tunis</p>
        </div>
        <div>
            <i class="fa fa-phone"></i>
            <p>+216 25 438 004</p>
        </div>
        <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:support@company.com">CollabSpot@company.com</a></p>
        </div>
    </div>
    <div class="footer-right">
        <p class="footer-company-about">
            <span>About the company</span>
            Welcome to CollabSpot, a professional networking platform designed to connect individuals,
            foster meaningful professional relationships, and empower career growth. Build your professional
            identity, showcase your skills, and explore new opportunities in a dynamic community dedicated
            to advancing careers and fostering collaboration
        </p>
    </div>
</footer>
<!-- Modal -->
<script src="controle\controle.js"></script>
<script src="controle\controle1.js"></script>