<nav class="nav-bar">
    <a href="../design/user.php"><i class="bi bi-arrow-left-circle"></i></a>
    <div class="searche">
        <i class="bi bi-search"></i>
        <input type="text" id="recherche" placeholder="searche...">
    </div>

    <div class="menu">
        <i class="bi bi-envelope-fill"></i>
        <i class="bi bi-bell-fill"></i>
        <i class="bi bi-list"></i>
    </div>
</nav>
<div class="Photo-de-couverture">
    <?php if($user['photoCouverture']) { ?>
        <img src="<?= $user['photoCouverture'] ?>">
    <?php } else { ?>
        <img src="./assets/photo-de-couverture.png" width="100px">
    <?php } ?>    
</div>
<section class="profile">
    <div class="profile-user">
        <?php if(strlen($user['photoProfile'])!=0){ ?>
            <img src="<?="../".$user['photoProfile']?>">
        <?php }else{ ?>
            <img src="./assets/profil-avatar-homme-icone-ronde_24640-14044.png" width="100px">
        <?php  }?>
        <div class="name">
            <h1><?= $user['prenom'].' '.$user['nom'] ?></h1>
            <span><?= $user['metier'] ?></span>
            <i class="bi bi-calendar"></i>
        </div>
        <div class="follow">
            <div class="edit">
                <i class="bi bi-pencil-square"></i>
                <a href="modify.php?id=<?= $user['idUtilisateur'] ?>">Edit Profile</a>
            </div>
            <div class="add">
                <i class="bi bi-plus-lg"></i>
                <span>Add a story</span>
            </div>
        </div>
        <div class="details">
            <div>
                <?php if(isset($user['Photos'])){ ?>
                <p><?= $user['Photos'] ?></p>
                <?php } ?>
                <span>Photos</span>
            </div>
            <div>
            <?php if(isset($user['Followers'])){ ?>
                <p><?= $user['Followers'] ?></p>
                <?php } ?>
                <span>Followers</span>
            </div>
          
        </div>

    </div>
</section>
<br>
<section>
    <div class="information">
        <div class="about">
            <h2>About</h2>
        </div>
        <div class="publication">
            <div class="publication1">
                <?php if($user['photoProfile']){ ?>
                    <img src="<?="../".$user['photoProfile']?>">
                <?php }else if ($user['genre'] == "male") { ?>
                    <img src="assets/profil-avatar-homme-icone-ronde_24640-14044.png">
                <?php } else { ?>
                    <img src="assets/profil-avatar-femme-icone-ronde_24640-14042.png">
                <?php } ?>
                <h3><?= $user['prenom'].' '.$user['nom'] ?></h3>
            </div>
        </div>
    </div>
</section>
<footer>
    <h1>................................................</h1>
</footer>