<div class="loading">Loading&#8230;</div>
<nav class="shadow p-3 mb-5 bg-white rounded">
    <div class="nav-content" id="logo"><img src="../assets/icons/CollabSpot-removebg-preview.png" width="150px"
            height="150px"></div>
    <div class="nav-content" id="barre-rech">
        <form style="display:flex" action="friends-search.php" method="GET">
            <button type="submit" class="btn btn-outline-primary me-2" width="200px"><svg
                    xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-search mb-2" viewBox="0 0 16 16">
                    <path
                        d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
                </svg></button><input required class="form-control me-2" type="text"
                placeholder="Chercher un étudiant..." name="search_friends" aria-label="Search" id="search_etud">
    </div>
    </form>
    <div class="nav-content" id="icons">
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <div><img src="../assets/icons/bell-fill.svg"></div>
            </a>
            <ul class="dropdown-menu" style="width:600px;">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
        </div>
        <a class="dropdown-item" href="../message/index.php"><img src="../assets/icons/envelope-fill.svg"></a>
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <div><img src="../assets/icons/list.svg"></div>
            </a>
            <ul class="dropdown-menu" style="width:100px;">
                <li><a class="dropdown-item" href="../design/user.php">Home</a></li>
                <li><a class="dropdown-item" href="../profile/profile.php">Profile</a></li>
                <li><a class="dropdown-item" href="../message/index.php">Go chat </a></li>
                <li><a class="dropdown-item" href="../disconnect/disconnect.php">Disconnect</a></li>
            </ul>
        </div>
    </div>
</nav>
<?php if (isset($msg) && $msg==1) { ?>
<div class="container friends-search ">
    <div class="alert alert-success" role="alert" style="width:18rem;">
        amis trouvées!!;
    </div>
    <?php 
      foreach ($friends as $key) :
    ?>
    <div class="card" style="height: 12rem; width:18rem;">
        <div class="friend-search"><img src="../<?=$key['photoProfile']?>" width="100px" height="80px">
            <span class="ms-2 span-friend">
                <?=$key['nom'].' '.$key['prenom']?>
            </span>
        </div>
        <a href="friend-request.php?id_ami=<?=$key['idUtilisateur']; ?>"><button class="btn btn-primary">ajouter
                ami</button></a>
    </div>
    <?php
      endforeach;
    }else{
      if(isset($msg))
      { 
    ?>
    <div class="container friends-search ">
        <div class="alert alert-danger" role="alert" style="width:18rem;">
            amis non trouvées!!;
        </div>
    </div>
    <?php  } } ?>
</div>
<section>
    <div class=" shadow p-3 mb-5 bg-white rounded" id="user">
        <div id="user-sector"> <img style="border-radius: 50%;" src="./<?=$user['photoProfile']?>"><a
                href="../profile/profile.php"><span>
                    <?=$user['nom'].' '.$user['prenom'] ?>
                </span></a></div>
        <div class="mt-5 span-friends"> <span>friends-request:</span></div>
        <div id="requests">
            <?php if(isset($friends_req)):?>
            <?php  foreach($friends_req as $key): ?>
            <div class="card mt-2 friends-request shadow p-3 mb-5 bg-white rounded">
                <?php  //echo count($friends_request) ; ?>
                <div class="req-content">
                    <img src="../<?=$key['photoProfile']?>">
                    <span>
                        <?=$key['prenom'].' '.$key['nom'] ?>
                    </span>
                </div>
                <div class="mt-1 buttons " style="justify-content:center"><a
                        href="friend-accept.php?id_ami=<?=$key['idUtilisateur'] ?>" class="me-2"><button
                            class="btn btn-primary">confirmer</button></a><a
                        href="friend-delete.php?id_ami=<?=$key['idUtilisateur'] ?>"><button
                            class="btn  btn-secondary">annuler</button></a></div>
            </div>
            <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
    <div class="inner-section  shadow p-3 mb-5 bg-white rounded" id="user-section">
        <div id="amis" class="card">
            <div><img class="prfile-picture" src="../assets/icons/profile2.png"></div>
            <div><img class="prfile-picture" src="../assets/icons/profile1.png"></div>
            <div><img class="prfile-picture" src="../assets/icons/profile3.png"></div>
            <div><img class="prfile-picture" src="../assets/icons/profile4.png"></div>
            <div><img class="prfile-picture" src="../assets/icons/profile5.png"></div>
            <div><img class="prfile-picture" src="../assets/icons/profile1.png"></div>
        </div>
        <div id="publication" class="card">
            <form action="post.php" method="POST" id="publication" enctype="multipart/form-data">
                <div id="page-content1">
                    <img id="user-profile" style="border-radius: 50%;margin-top:5px;" class="profile-picture"
                        width="80px" height="80px" src="./<?=$user['photoProfile']?>">
                    <div id="input">
                        <input class="form-control me-2" type="text" name="pub"
                            placeholder="What's new <?= $user['prenom'] ?>..." aria-label="Search">
                    </div>
                </div>
                <div id="page-content2">
                    <div class="image-profile">
                        <img src="../assets/icons/camera-video.png" alt="">
                        <span>
                            <div class="custom-file-input">
                                <input type="file" name="video" id="customImageInput">
                                <span for="customImageInput" id="cursor">Video</span>
                            </div>
                        </span>
                    </div>
                    <div class="image-profile"><img src="../assets/icons/galerie.png" alt="">
                        <span>
                            <div class="custom-file-input">
                                <input type="file" name="image" id="customImageInput">
                                <span for="customImageInput" id="cursor">image</span>
                            </div>
                        </span>
                    </div>
                    <div class="image-profile"><img src="../assets/icons/date-du-calendrier.png" alt="">
                        <span>
                            <div class="custom-file-input">
                                <input type="file" name="event" id="customImageInput">
                                <span for="customImageInput" id="cursor">Event</span>
                            </div>
                        </span>
                    </div>
                </div>
                <br>
                <div id="page-content3" class="me-5">
                    <button class="btn btn-primary col-md-5" name="submit">submit</button>
                </div>
            </form>
        </div>
        <div id="page" class="card">
            <?php foreach($res as $publication):
          $sql='select * from utilisateur where idUtilisateur=?';
          $user_req=$pdo->prepare($sql);
          $user_req->execute([$publication['idUtilisateur']]);
          $user=$user_req->fetch();
          ?>
            <div class="card1">
                <div class="top1">
                    <div class="user_details1">
                        <div class="profile_img1">
                            <img src="./<?=$user['photoProfile'] ?>" alt="user" class="cover1">
                        </div>
                        <h3>
                            <?=$user['prenom'].' '.$user['nom'] ?><br><span class="hour1">20 h</span>
                            <span class="globDot1">.</span>
                        </h3>
                    </div>
                    <div class="dot1">
                        <img src="../assets/dot.png" alt="dot">
                    </div>
                </div>
                <p class="message1">
                    <?= $publication['contenuPub']?>
                </p>
                <?php if (!empty($publication['image']) || !empty($publication['video'])) { ?>
                <div class="imgBg1">
                    <?php if (!empty($publication['image'])) { ?>
                    <img src="./<?= $publication['image'] ?>" alt="bg" class="coverFull1">
                    <?php } else { ?>
                    <?php if (!empty($publication['video'])) { ?>
                    <div class="coverFull1">
                        <video width="320" height="240" controls>
                            <source src="<?=$publication['video'] ?>" type="video/mp4">
                        </video>
                    </div>
                    <?php }
                } ?>
                </div>
                <?php } ?>
                <div class="btns1">
                    <div class="left1">
                        <img src="../assets/like.png" alt="like">
                        <h4 class="likes1">499</h4>
                    </div>
                    <div class="right1">
                        <h4>919 comments 500 shares</h4>
                    </div>
                </div>
                <div class="border1"></div>
                <div class="icon1">
                    <div class="like1">
                        <img src="../assets/gray_like.png" alt="like" class="graylike" onclick="likeButton()">
                        <img src="../assets/comments.png" alt="comments">
                        <img src="../assets/share.png" alt="share">
                    </div>
                </div>
            </div>
            <?php endforeach;?>
        </div>
    </div>
    </div>
    <div class="inner-section  shadow p-3 mb-5 bg-white rounded" id="notifications">
        <span><b>Friends</b></span>
        <div id="friends">
            <?php if(isset($friends_res)): ?>
            <?php  foreach($friends_res as $key):?>
            <div class="card mt-2 friends-request shadow p-3 mb-5 bg-white rounded">
                <?php  //echo count($friends_request) ; ?>
                <div class="req-content">
                    <img src="../<?=$key['photoProfile']?>">
                    <span>
                        <?=$key['prenom'].' '.$key['nom'] ?>
                    </span>
                </div>
                <div class="mt-1 buttons " style="justify-content:center"><a
                        href="../profile/profile.php?id_ami=<?=$key['idUtilisateur'] ?>" class="me-2"><button
                            class="btn btn-primary">Voir profile</button></a></div>
            </div>
            <?php  endforeach; endif;?>
        </div>
    </div>

</section>