<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="./discussion.scss">
  <link rel="stylesheet" href="../design/style.css">
  <title>Document</title>
</head>

<body>
  <div class="app">
  <nav class="shadow p-3 mb-5 bg-white rounded">
    <div class="nav-content" id="logo"><img src="../assets/icons/CollabSpot-removebg-preview.png" width="150px" height="150px"></div>
    <div class="nav-content" id="barre-rech" ><form style="display:flex" action="friends-search.php" method="GET">
     <button type="submit"class="btn btn-outline-primary me-2" width="200px"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search mb-2" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
        </svg></button><input required class="form-control me-2" type="text" placeholder="Chercher un étudiant..." name="search_friends" aria-label="Search" id="search_etud"></div>
        </form>
        <div class="nav-content" id="icons">
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <div><img src="../assets/icons/bell-fill.svg"></div>
        </a>
        <ul class="dropdown-menu" style="width:600px;">
          <li><a class="dropdown-item" href="#">Action</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
      </div>
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <div><img src="../assets/icons/envelope-fill.svg"></div>
        </a>
        <ul class="dropdown-menu" style="width:600px;">
          <li><a class="dropdown-item" href="#">Action</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
      </div>
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <div><img src="../assets/icons/list.svg"></div>
        </a>
        <ul class="dropdown-menu" style="width:100px;">
          <li><a class="dropdown-item" href="../design/user.php">Home</a></li>
          <li><a class="dropdown-item" href="../profile/profile.php">Profile</a></li>
          <li><a class="dropdown-item" href="../message/index.php">Go chat </a></li>
          <li><a class="dropdown-item" href="../disconnect/disconnect.php">Disconnect</a></li>
          
        </ul>
      </div>
    </div>
  </nav>
    <div class="wrapper">
      <div class="conversation-area">
        <?php
        if (isset($infosAmis)) {
          foreach ($infosAmis as $ami) {
        ?>
            <div class="msg active">
              <div class="msg-profile group">
                <img src="../<?= $ami['photoProfile'] ?>">

                </svg>
              </div>
              <div class="msg-detail">
                <div class="msg-username"><?php echo $ami['nom'] . ' ' . $ami['prenom']; ?></div>
                <div class="msg-content">
                  <?php if (isset($ami['lastMessage'])) : ?>
                    <span class="msg-message"><?php echo $ami['lastMessage']['contenu']; ?></span>
                    <span class="msg-date"><?php echo $ami['lastMessage']['date']; ?></span>
                  <?php else : ?>
                    <span class="msg-message">Aucun message</span>
                    <span class="msg-date">-</span>
                    <a href="index.php?id_ami=<?= $ami['idUtilisateur'] ?>"> <button class="btn btn-primary">Chat</button></a>
                  <?php endif; ?>
                </div>
              </div>
            </div>
        <?php
          }
        }
        ?>
        <button class="add"></button>
        <div class="overlay"></div>
      </div>
      <div class="chat-area">
        <div class="chat-area-header">
          <div class="chat-area-group">
            <img class="chat-area-profile" src="../assets/akrem.jpg" alt="" />
          </div>
        </div>
        <div class="chat-area-main">

          <?php if (isset($results_message_ami)) :
            foreach ($results_message_ami as $msg) :
              if ($msg['idEmetteur'] == $profile_user['idUtilisateur']) {
          ?>
                <div class="chat-msg owner">
                  <div class="chat-msg-profile">
                    <img class="chat-msg-img" src="../<?= $profile_user['photoProfile'] ?>" alt="" />
                    <div class="chat-msg-date"><?= $msg['dateMsg'] ?></div>
                  </div>
                  <div class="chat-msg-content">
                    <div class="chat-msg-text"><?= $msg['contenuMsg'] ?></div>
                  </div>
                </div>
              <?php } else {  ?>
                <div class="chat-msg">
                  <div class="chat-msg-profile">
                    <img class="chat-msg-img" src="../<?= $profile_ami['photoProfile']  ?>" alt="" />
                    <div class="chat-msg-date"><?= $msg['dateMsg'] ?></div>
                  </div>
                  <div class="chat-msg-content">
                    <div class="chat-msg-text"><?= $msg['contenuMsg'] ?></div>
                  </div>
                </div>
              <?php }; ?>
          <?php endforeach;
          endif; ?>

          <!-- ami section -->

          <!-- ends here -->
          <!-- owner -->
          <div class="chat-msg">
            <div class="chat-msg-profile">
              <img class="chat-msg-img" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3364143/download+%282%29.png" alt="">
              <div class="chat-msg-date">Message seen 3.16pm</div>
            </div>
            <div class="chat-msg-content">
              <div class="chat-msg-text">Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et🥰</div>
            </div>
          </div>
          <!--owner ends here -->
        </div>
        <form action="index.php?id_ami=<?=$id_ami ?>" method="POST">
          <div class="chat-area-footer">

            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-video">
              <path d="M23 7l-7 5 7 5V7z" />
              <rect x="1" y="5" width="15" height="14" rx="2" ry="2" />
            </svg>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-image">
              <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
              <circle cx="8.5" cy="8.5" r="1.5" />
              <path d="M21 15l-5-5L5 21" />
            </svg>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle">
              <circle cx="12" cy="12" r="10" />
              <path d="M12 8v8M8 12h8" />
            </svg>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-paperclip">
              <path d="M21.44 11.05l-9.19 9.19a6 6 0 01-8.49-8.49l9.19-9.19a4 4 0 015.66 5.66l-9.2 9.19a2 2 0 01-2.83-2.83l8.49-8.48" />
            </svg>
            <input type="text" placeholder="Type something here..." name="message" /><input>
            <?php  if(isset($id_ami)): ?>
            <input type="hidden" value="<?=$id_ami?>" name="id_ami">
            <?php endif; ?>
            <button type="submit" name="submit" class="btn btn-primary">send</button>

          </div>
        </form>
      </div>
      <div class="detail-area">
        <div class="detail-area-header">
          <div class="msg-profile group">
            <img src="../assets/48107a1c8c80edaedcd256541eec1431.png" style="border-radius:20%">
          </div>
          <div class="detail-title">CollabSpot Group</div>
          <div class="detail-subtitle">Created by Akram, 2 december 2023</div>
          <div class="detail-buttons">
            <button class="detail-button">
              <svg viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="currentColor" stroke="currentColor" stroke-width="0" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone">
                <path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72 12.84 12.84 0 00.7 2.81 2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45 12.84 12.84 0 002.81.7A2 2 0 0122 16.92z" />
              </svg>
              Call Group
            </button>
            <button class="detail-button">
              <svg viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="currentColor" stroke="currentColor" stroke-width="0" stroke-linecap="round" stroke-linejoin="round" class="feather feather-video">
                <path d="M23 7l-7 5 7 5V7z" />
                <rect x="1" y="5" width="15" height="14" rx="2" ry="2" />
              </svg>
              Video Chat
            </button>
          </div>
        </div>
        <div class="detail-changes">
          <input type="text" placeholder="Search in Conversation">
          <div class="detail-change">
            Change Color
            <div class="colors">
              <div class="color blue selected" data-color="blue"></div>
              <div class="color purple" data-color="purple"></div>
              <div class="color green" data-color="green"></div>
              <div class="color orange" data-color="orange"></div>
            </div>
          </div>
          <div class="detail-change">
            Change Emoji
            <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up">
              <path d="M14 9V5a3 3 0 00-3-3l-4 9v11h11.28a2 2 0 002-1.7l1.38-9a2 2 0 00-2-2.3zM7 22H4a2 2 0 01-2-2v-7a2 2 0 012-2h3" />
            </svg>
          </div>
        </div>
        <div class="detail-photos">
          <div class="detail-photo-title">
            <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-image">
              <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
              <circle cx="8.5" cy="8.5" r="1.5" />
              <path d="M21 15l-5-5L5 21" />
            </svg>
            Shared photos
          </div>
          <div class="detail-photo-grid">
            <img src="https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2168&q=80" />
            <img src="https://images.unsplash.com/photo-1516085216930-c93a002a8b01?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" />
            <img src="https://images.unsplash.com/photo-1458819714733-e5ab3d536722?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=933&q=80" />
            <img src="https://images.unsplash.com/photo-1520013817300-1f4c1cb245ef?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2287&q=80" />
            <img src="https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2247&q=80" />
            <img src="https://images.unsplash.com/photo-1559181567-c3190ca9959b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1300&q=80" />
            <img src="https://images.unsplash.com/photo-1560393464-5c69a73c5770?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1301&q=80" />
            <img src="https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2249&q=80" />
            <img src="https://images.unsplash.com/photo-1481349518771-20055b2a7b24?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2309&q=80" />

            <img src="https://images.unsplash.com/photo-1473170611423-22489201d919?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2251&q=80" />
            <img src="https://images.unsplash.com/photo-1579613832111-ac7dfcc7723f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" />
            <img src="https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2189&q=80" />
          </div>
          <div class="view-more">View More</div>
        </div>
        <a href="https://twitter.com/AysnrTrkk" class="follow-me" target="_blank">
          <span class="follow-text">
            <svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1">
              <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path>
            </svg>
            Follow me on Twitter
          </span>
          <span class="developer">
            <img src="https://pbs.twimg.com/profile_images/1253782473953157124/x56UURmt_400x400.jpg" />
            Aysenur Turk — @AysnrTrkk
          </span>
        </a>
      </div>
    </div>
  </div>
  <script src="./discussion.js"></script>
</body>

</html>